---

- name: Download Atom x86_64 package for Debian OS family
  get_url:
    url: https://atom.io/download/deb
    dest: /var/tmp/atom-x86_64.deb
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'x86_64'
  tags:
    - atom

- name: Install Atom x86_64 package for Debian OS family
  apt:
    deb: /var/tmp/atom-x86_64.deb
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'x86_64'
  tags:
    - atom

- name: Install additional Atom packages per user
  command: "apm install {{item.1}}"
  become: yes
  become_user: "{{item.0.user}}"
  with_subelements:
    - "{{atom_packages_per_user}}"
    - packages
  tags:
    - atom
